[weather_data_idx]
coldPath = $SPLUNK_DB/weather_data_idx/colddb
homePath = $SPLUNK_DB/weather_data_idx/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/weather_data_idx/thaweddb

[forecast]
coldPath = $SPLUNK_DB/forecast/colddb
homePath = $SPLUNK_DB/forecast/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/forecast/thaweddb
