[weather_data]
start_by_shell = false
python.version = python3
sourcetype = openweathermap:json
interval = 3600
disabled = 0

[weather_data://openweather]
api_key = ******
city = kazanlak
index = weather_data_idx
interval = 3600

