[admin:TA_mincho_praznikov]
match = /
members = TA_mincho_praznikov_settings, TA_mincho_praznikov_weather_data

[admin_external:TA_mincho_praznikov_settings]
handlertype = python
python.version = python3
handlerfile = TA_mincho_praznikov_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_mincho_praznikov_weather_data]
handlertype = python
python.version = python3
handlerfile = TA_mincho_praznikov_rh_weather_data.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

