
[expose:TA_mincho_praznikov_settings]
pattern = TA_mincho_praznikov_settings
methods = POST, GET

[expose:TA_mincho_praznikov_settings_specified]
pattern = TA_mincho_praznikov_settings/*
methods = POST, GET, DELETE

[expose:TA_mincho_praznikov_weather_data]
pattern = TA_mincho_praznikov_weather_data
methods = POST, GET

[expose:TA_mincho_praznikov_weather_data_specified]
pattern = TA_mincho_praznikov_weather_data/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET

